### ISSUE TITLE
Wrong NUMBER_OF_PEOPLE_IN_SPACE returned

### ISSUE THREAD

**Issue by AndreyKopeyko** [open-notify/Open-Notify-API#42]
I checked now [astros.json](http://api.open-notify.org/astros.json) and see that it doesn't count Chinese taikonauts as human beings being in space right now. :-(

According to https://en.wikipedia.org/wiki/Tiangong_space_station#Crewed_missions
from 2024-04-25 we have 3 more humans in near Earth space.

So, the correct `NUMBER_OF_PEOPLE_IN_SPACE` should be 10 for today.

Can you please take Chinese into account too?
I would like to have a precise data source for my pet project.

**Comment by radziejewicz** [comment]
Bump, same issue.

**Comment by radziejewicz** [comment]
@AndreyKopeyko 

I think that at the moment the project is dead :(

**Comment by AndreyKopeyko** [comment]
Seems like this issue was fixed silently - now I can see 3 taikonauts in astros.json output
```
kaa@NCTnb2:~/work$ curl -s http://api.open-notify.org/astros.json |jq
{
  "people": [
    {
      "craft": "ISS",
      "name": "Oleg Kononenko"
    },
    {
      "craft": "ISS",
      "name": "Nikolai Chub"
    },
    {
      "craft": "ISS",
      "name": "Tracy Caldwell Dyson"
    },
    {
      "craft": "ISS",
      "name": "Matthew Dominick"
    },
    {
      "craft": "ISS",
      "name": "Michael Barratt"
    },
    {
      "craft": "ISS",
      "name": "Jeanette Epps"
    },
    {
      "craft": "ISS",
      "name": "Alexander Grebenkin"
    },
    {
      "craft": "ISS",
      "name": "Butch Wilmore"
    },
    {
      "craft": "ISS",
      "name": "Sunita Williams"
    },
    {
      "craft": "Tiangong",
      "name": "Li Guangsu"
    },
    {
      "craft": "Tiangong",
      "name": "Li Cong"
    },
    {
      "craft": "Tiangong",
      "name": "Ye Guangfu"
    }
  ],
  "number": 12,
  "message": "success"
}
kaa@NCTnb2:~/work$ 
```

**Comment by HeadBoffin** [comment]
Still returning the same result, 14th Apr 2025, well after the return to Earth of Butch & Sunita.

Such a shame this can't be fully automated as makes for a great student project.

**Comment by KrogerKing** [comment]
Still showing the incorrect number of peeps.
I am not certain the location info is correct either.   
Hopefully someone smarter than me can fix this haha

**Comment by fyford** [comment]
Still seeing 12 ... should be only 10

**Comment by tonvanbart** [comment]
For anyone following this issue: https://corquaid.github.io/international-space-station-APIs/JSON/people-in-space.json is more actively maintained at this moment.
